# Generated by Django 4.2.6 on 2023-10-15 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('contact_no', models.CharField(max_length=150, null=True)),
                ('email_id', models.EmailField(max_length=254, null=True)),
                ('location', models.TextField(null=True)),
                ('patient_case', models.CharField(max_length=150, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('profile_photo', models.ImageField(null=True, upload_to='profile-upload/patient/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PatientProfiles',
                'verbose_name_plural': 'PatientProfiles',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialization', models.CharField(max_length=150, null=True)),
                ('qualification', models.CharField(max_length=150, null=True)),
                ('works_at', models.CharField(max_length=150, null=True)),
                ('contact_no', models.CharField(max_length=150, null=True)),
                ('email_id', models.EmailField(max_length=254, null=True)),
                ('location', models.TextField(null=True)),
                ('profile_photo', models.ImageField(null=True, upload_to='profile-upload/doctor/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DoctorProfiles',
                'verbose_name_plural': 'DoctorProfiles',
            },
        ),
    ]
